import { Image, View, StyleSheet } from "react-native";

const images = {
  flowers: {
    c1: require("../assets/image/cuc_1.jpg"),
    c2: require("../assets/image/cuc_2.jpg"),
    c3: require("../assets/image/cuc_3.jpg"),
    c4: require("../assets/image/cuc_4.jpg"),
    c5: require("../assets/image/cuc_5.jpg"),
    c6: require("../assets/image/cuc_6.jpg"),
    c7: require("../assets/image/cuc_7.jpg"),
    c8: require("../assets/image/cuc_8.jpg"),
    c9: require("../assets/image/cuc_9.jpg"),
    c10: require("../assets/image/cuc_10.jpg"),
    c11: require("../assets/image/cuc_11.jpg"),
    c12: require("../assets/image/cuc_12.jpg"),
    c13: require("../assets/image/cuc_13.jpg"),
    c14: require("../assets/image/cuc_14.jpg"),
    c15: require("../assets/image/cuc_15.jpg"),
    c16: require("../assets/image/cuc_16.jpg"),
    ci1: require("../assets/image/cuoi_1.jpg"),
    ci2: require("../assets/image/cuoi_2.jpg"),
    ci3: require("../assets/image/cuoi_3.jpg"),
    ci4: require("../assets/image/cuoi_4.jpg"),
    ci5: require("../assets/image/cuoi_5.jpg"),
    ci6: require("../assets/image/cuoi_6.jpg"),
    ci7: require("../assets/image/cuoi_7.jpg"),
    ci8: require("../assets/image/cuoi_8.jpg"),
    ci9: require("../assets/image/cuoi_9.jpg"),
    h1: require("../assets/image/hong_1.jpg"),
    h2: require("../assets/image/hong_2.jpg"),
    h3: require("../assets/image/hong_3.jpg"),
    h4: require("../assets/image/hong_4.jpg"),
    h5: require("../assets/image/hong_5.jpg"),
    h7: require("../assets/image/hong_7.jpg"),
    h8: require("../assets/image/hong_8.jpg"),
    h9: require("../assets/image/hong_9.jpg"),
    h10: require("../assets/image/hong_10.jpg"),
    h11: require("../assets/image/hong_11.jpg"),
    h12: require("../assets/image/hong_12.jpg"),
    h13: require("../assets/image/hong_13.jpg"),
    h14: require("../assets/image/hong_14.jpg"),
    h15: require("../assets/image/hong_15.jpg"),
    h16: require("../assets/image/hong_16.jpg"),
    x1: require("../assets/image/xuan_1.jpg"),
    x2: require("../assets/image/xuan_2.jpg"),
    x3: require("../assets/image/xuan_3.jpg"),
    x4: require("../assets/image/xuan_4.jpg"),
    x5: require("../assets/image/xuan_5.jpg"),
    x6: require("../assets/image/xuan_6.jpg"),
    x7: require("../assets/image/xuan_7.jpg"),
    x8: require("../assets/image/xuan_8.jpg"),
    x9: require("../assets/image/xuan_9.jpg"),
  },
};

export default images;
